EXIT_COMMAND: str = 'exit'
'''
Exit voltpeek program.
'''
TRIGGER_COMMAND: str = 'trigger'
AUTO_TRIGGER_COMMAND: str = 'atrigger'
NORMAL_TRIGGER_COMMAND: str = 'ntrigger'
SINGLE_TRIGGER_COMMAND: str = 'strigger'
CONNECT_COMMAND: str = 'connect'
SCALE_COMMAND: str = 'scale'
FAKE_TRIGGER_COMMAND: str = 'faketrigger'
TRIGGER_LEVEL_COMMAND: str = 'triglevel'
TRIGGER_RISING_EDGE_COMMAND: str = 'trigrising'
TRIGGER_FALLING_EDGE_COMMAND: str = 'trigfalling'
TOGGLE_CURS: str = 'togglecurs'
TOGGLE_HCURS: str = 'togglehcurs'
TOGGLE_VCURS: str = 'togglevcurs'
ADJUST_CURS: str = 'adjustcurs'
NEXT_CURS: str = 'nextcurs'
PROBE_1: str = 'probe1'
PROBE_10: str = 'probe10'
STOP: str = 'stop'
CAL: str = 'cal'
PNG: str = 'png'

ADJUST_COMMANDS: tuple[str, str, str] = (SCALE_COMMAND, TRIGGER_LEVEL_COMMAND, ADJUST_CURS)